Book.destroy_all
Book.create([
    {
        title: "How to Win Friends and Influence People",
        subtitle: "The Only Book You Ned to Lead You to Success",
        author: "Dale Carnegie",
        image_address: "win_friends_influence.jpg",
        image_alt: "Alex Younger ReadingList How to Win Friends and Influence People by Dale Carnegie",
        category: "peopleskill",
        book_link: "http://www.alextheyounger.me/articles/24",
    },
    {
        title: "The Daily Stoic",
        subtitle: "366 Meditations on Wisdom, Perseverance, and the Art of Living",
        author: "Ryan Holiday",
        image_address: "daily_stoic.jpg",
        image_alt: "Alex Younger ReadingList The Daily Stoic by Ryan Holiday",
        category: "philosophy",
        book_link: "http://www.alextheyounger.me/articles/25",
    },
    {
        title: "Foundations of Morality",
        author: "Henry Hazlitt",
        image_address: "foundations_morality.jpg",
        image_alt: "Alex Younger ReadingList Foundations of Morality by Henry Hazlitt",
        category: "philosophy",
        book_link: "https://mises.org/library/foundations-morality"
    },
    {
        title: "The Antidote",
        subtitle: "Happiness For People Who Can't Stand Positive Thinking",
        author: "Oliver Burkeman",
        image_address: "the_antidote.jpg",
        image_alt: "Alex Younger ReadingList The Antidote: Happiness For People Who Can't Stand Positive Thinking by Oliver Burkeman",
        category: "better-living",
        book_link: "https://www.amazon.com/Antidote-Happiness-People-Positive-Thinking/dp/0865478015/ref=sr_1_1?s=books&ie=UTF8&qid=1515919681&sr=1-1&keywords=the+antidote+happiness+for+people+who+can%27t+stand+positive+thinking"
    },
    {
        title: "Square One",
        subtitle: "The Foundations of Knowledge",
        author: "Steve Patterson",
        image_address: "square_one.jpg",
        image_alt: "Alex Younger ReadingList Square One: The Foundations of Knowledge by Steve Patterson",
        category: "philosophy",
        book_link: "https://www.amazon.com/Square-One-Foundations-Steve-Patterson-ebook/dp/B01M9JL27L/ref=sr_1_1?ie=UTF8&qid=1515980663&sr=8-1&keywords=square+one+steve+patterson",
    },
    {
        title: "Making Economic Sense",
        author: "Murray Rothbard",
        image_address: "making_economic_sense.jpg",
        image_alt: "Alex Younger ReadingList Making Economic Sense by Murray Rothbard",
        category: "econ",
        book_link: "https://mises.org/library/making-economic-sense",
    },
    {
        title: "Good Profit",
        subtitle: "How Creating Value for Others Built One of the World's Most Successful Companies",
        author: "Charles Koch",
        image_address: "good_profit.jpg",
        image_alt: "Alex Younger ReadingList Good Profit by Charles Koch",
        category: "biz",
        book_link: "https://www.amazon.com/Good-Profit-Creating-Successful-Companies/dp/1101904135/ref=sr_1_1?s=books&ie=UTF8&qid=1515919796&sr=1-1&keywords=good+profit+charles+koch",
    },
    {
        title: "A Guide to the Good Life",
        subtitle: "The Ancient Art of Stoic Joy",
        author: "William B. Irvine",
        image_address: "good_life.jpg",
        image_alt: "Alex Younger ReadingList A Guide to the Good Life by William B. Irvine",
        category: "better-living",
        book_link: "https://www.amazon.com/Guide-Good-Life-Ancient-Stoic/dp/0195374614/ref=sr_1_1?s=books&ie=UTF8&qid=1515918746&sr=1-1&keywords=a+guide+to+the+good+life",
    },
    {
        title: "The Solution to Social Anxiety",
        subtitle: "Break Free from the Shyness That Holds You Back",
        author: "Dr. Aziz Gazipura",
        image_address: "social_anxiety.jpg",
        image_alt: "Alex Younger ReadingList The Solution to Social Anxiety by Dr. Aziz Gazipura",
        category: "better-living",
        book_link: "https://www.amazon.com/Solution-Social-Anxiety-Break-Shyness-ebook/dp/B00F5IU5CU/ref=sr_1_2_sspa?s=books&ie=UTF8&qid=1515919521&sr=1-2-spons&keywords=solution+to+social+anxiety&psc=1",
    },
    {
        title: "Notes on Democracy",
        author: "H.L. Mencken",
        image_address: "notes_on_democracy.jpg",
        image_alt: "Alex Younger ReadingList Notes on Democracy by H.L. Mencken",
        category: "pol",
        book_link: "https://www.amazon.com/Notes-Democracy-Large-Print-Mencken/dp/1494288648/ref=sr_1_1?s=books&ie=UTF8&qid=1515919184&sr=1-1&keywords=notes+on+democracy",
    },
    {
        title: "What is Real",
        subtitle: "The Unfinished Quest for the Meaning of Quantum Physics",
        author: "Adam Becker",
        image_address: "what_is_real.jpg",
        image_alt: "Alex Younger ReadingList What is Real by Adam Becker",
        category: "science",
        book_link: "https://www.amazon.com/What-Real-Unfinished-Meaning-Quantum/dp/0465096050",
    },
    {
        title: "Waking Up",
        subtitle: "A Guide to Spirituality Without Religion",
        author: "Sam Harris",
        image_address: "waking_up.jpg",
        image_alt: "Alex Younger ReadingList Waking Up by Sam Harris",
        category: "philosophy",
        book_link: "https://www.amazon.com/Waking-Up-Spirituality-Without-Religion/dp/1451636024/ref=sr_1_1?s=books&ie=UTF8&qid=1515920029&sr=1-1&keywords=waking+up+sam+harris",
    },
    {
        title: "Out of Your Mind",
        subtitle: "Essential Listening from the Alan Watts Archives",
        author: "Alan Watts",
        image_address: "out_of_your_mind.jpg",
        image_alt: "Alex Younger ReadingList Out of Your Mind",
        category: "philosophy",
        book_link: "https://www.amazon.com/Out-of-Your-Mind/dp/B0162WIRKY/ref=sr_1_2?ie=UTF8&qid=1517010662&sr=8-2&keywords=out+of+your+mind+by+alan+watts",
    },
    {
        title: "You're It",
        subtitle: "On Hiding, Seeking, and Being Found",
        category: "philosophy",
        image_address: "youre_it.jpg",
        book_link: "https://www.amazon.com/Youre-Hiding-Seeking-Being-Found/dp/1591797349",
        image_alt: "Alex Younger ReadingList You're It by Alan Watts",
        author: "Alan Watts",
    },
    {
        title: "Street Smarts",
        category: "finance",
        image_address: "street_smarts.jpg",
        book_link: "https://www.amazon.com/Street-Smarts-Adventures-Road-Markets/dp/0307986071/ref=sr_1_1?s=books&ie=UTF8&qid=1515923486&sr=1-1&keywords=street+smarts+jim+rogers",
        image_alt: "Alex Younger ReadingList Street Smarts by Jim Rogers",
        author: "Jim Rogers",
    },
    {
        title: "The Charisma Myth",
        subtitle: "How Anyone Can Master the Art and Science of Personal Magnetism",
        category: "peopleskill",
        image_address: "charisma_myth.jpg",
        book_link: "https://www.amazon.com/Charisma-Myth-Science-Personal-Magnetism/dp/1591845947/ref=sr_1_1?s=books&ie=UTF8&qid=1515919947&sr=1-1&keywords=The+Charisma+Myth+by+Olivia+Fox+Cabane",
        image_alt: "Alex Younger ReadingList The Charisma Myth by Olivia Fox Cabane",
        author: "Olivia Fox Cabane",
    },
    {
        title: "Extraordinary Popular Delusions and the Madness of Crowds",
        category: "history",
        image_address: "madness_of_crowds.jpg",
        book_link: "https://www.amazon.com/Extraordinary-Popular-Delusions-Madness-Crowds/dp/1463740514/ref=sr_1_1?s=books&ie=UTF8&qid=1515920340&sr=1-1&keywords=extraordinary+popular+delusions+and+the+madness+of+crowds",
        image_alt: "Alex Younger ReadingList Extraordinary Popular Delusions and the Madness of Crowds by Charles Mackay",
        author: "Charles Mackay",
    },
    {
        title: "A Troublesome Inheritance",
        subtitle: "Genes, Race, and Human History",
        category: "science",
        image_address: "troublesome_inheritance.jpg",
        book_link: "https://www.amazon.com/Troublesome-Inheritance-Genes-Human-History/dp/0143127160/ref=sr_1_1?s=books&ie=UTF8&qid=1515921233&sr=1-1&keywords=a+troublesome+inheritance+by+nicholas+wade",
        image_alt: "Alex Younger ReadingList A Troublesome Inheritance by Nicholas Wade",
        author: "Nicholas Wade",
    },
    {
        title: "Why We Sleep",
        subtitle: "Unlocking the Power of Sleep and Dreams",
        category: "science",
        image_address: "why_we_sleep.jpg",
        book_link: "https://www.amazon.com/Why-We-Sleep-Unlocking-Dreams/dp/1501144316",
        image_alt: "Alex Younger ReadingList Unlocking the Power of Sleep and Dreams by Matthew Walker, PhD",
        author: "Matthew Walker, PhD",
    },
    {
        title: "Fool's Errand",
        subtitle: "Time to End the War in Afghanistan",
        category: "history",
        image_address: "fools_errand.jpg",
        book_link: "https://www.amazon.com/Fools-Errand-Time-End-Afghanistan/dp/1548650218",
        image_alt: "Alex Younger ReadingList https://images-na.ssl-images-amazon.com/images/I/51zrL6zS1ZL._SX331_BO1,204,203,200_.jpg",
        author: "Scott Horton",
    },
    {
        title: "The Failure of the New Economics",
        subtitle: "An Analysis of the Keynesian Fallacies",
        category: "econ",
        image_address: "failure_new_economics.jpg",
        book_link: "https://mises.org/library/failure-new-economics-0",
        image_alt: "Alex Younger ReadingList The Failure of the New Economics by Henry Hazlitt",
        author: "Henry Hazlitt",
    },
    {
        title: "The Righteous Mind",
        subtitle: "Why Good People are Divided by Politics and Religion",
        category: "psych",
        image_address: "righteous_mind.jpg",
        book_link: "https://www.amazon.com/Righteous-Mind-Divided-Politics-Religion/dp/0307455777/ref=sr_1_1?s=books&ie=UTF8&qid=1515921478&sr=1-1&keywords=jonathan+haidt+the+righteous+mind",
        image_alt: "Alex Younger ReadingList The Righteous Mind by Jonathan Haidt",
        author: "Jonathan Haidt",
    },
    {
        title: "Do What You Are",
        subtitle: "Discover the Perfect Career for You Through the Secrets of Personality Type",
        category: "psych",
        image_address: "do_what_you_are.jpg",
        book_link: "https://www.amazon.com/Do-What-You-Are-Personality/dp/031623673X/ref=sr_1_2?s=books&ie=UTF8&qid=1515924039&sr=1-2&keywords=do+what+you+are+paul+tieger",
        image_alt: "Alex Younger ReadingList Do What You Are by Paul D. Tieger, Barbara Barron, and Kelly Tieger",
        author: "Paul D. Tieger, Barbara Barron, and Kelly Tieger",
    },
    {
        title: "Mindfulness in Plain English",
        category: "productivity",
        image_address: "mindfulness_plain_english.jpg",
        book_link: "https://www.amazon.com/Mindfulness-Plain-English-Revised-Expanded/dp/0861713214/ref=sr_1_3?s=books&ie=UTF8&qid=1517263300&sr=1-3&keywords=mindfulness+in+plain+english",
        image_alt: "Alex Younger ReadingList Mindfulness in Plain English by Bhante Gunaratana",
        author: "Bhante Gunaratana",
    },
    {
        title: "Deep Work",
        subtitle: "Rules for Focused Success in a Distracted World",
        category: "productivity",
        image_address: "deep_work.jpg",
        book_link: "https://www.amazon.com/Deep-Work-Focused-Success-Distracted/dp/1455586692/ref=sr_1_1?s=books&ie=UTF8&qid=1515921725&sr=1-1&keywords=cal+newport+deep+work",
        image_alt: "Alex Younger ReadingList Deep Work by Cal Newport",
        author: "Cal Newport",
    },
    {
        title: "Deep Thoughts",
        subtitle: "Inspiration for the Uninspired",
        category: "misc",
        image_address: "deep_thoughts.jpg",
        book_link: "https://www.amazon.com/Deep-Thoughts-Inspiration-Jack-Handey/dp/0425133656",
        image_alt: "Alex Younger ReadingList Deep Thoughts by Jack Handey",
        author: "Jack Handey",
    },
    {
        title: "Total Recall",
        subtitle: "My Unbelievably True Life Story",
        category: "autobio",
        image_address: "total_recall.jpg",
        book_link: "https://www.amazon.com/Total-Recall-Unbelievably-True-Story/dp/1451662440/ref=sr_1_1?s=books&ie=UTF8&qid=1521363393&sr=1-1&keywords=total+recall+arnold+schwarzenegger",
        image_alt: "Alex Younger ReadingList Total Recall by Arnold Schwarzenegger",
        author: "Arnold Schwarzenegger",
    },   
    {
        title: "Hot Commodities",
        subtitle: "How Anyone Can Invest Profitably in the World's Best Market",
        category: "finance",
        image_address: "hot_commodities.jpg",
        book_link: "https://www.amazon.com/Hot-Commodities-Anyone-Invest-Profitably-ebook/dp/B000FC2OO8/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1515983311&sr=1-1&keywords=hot+commodities+jim+rogers",
        image_alt: "Alex Younger ReadingList Hot Commodities by Jim Rogers",
        author: "Jim Rogers",
    },
    {
        title: "The Millionaire Next Door",
        subtitle: "The Surprising Secrets of America's Wealthy",
        category: "finance",
        image_address: "millionaire_next_door.jpg",
        book_link: "https://www.amazon.com/Millionaire-Next-Door-Surprising-Americas/dp/1589795474/ref=sr_1_1?s=books&ie=UTF8&qid=1551049716&sr=1-1&keywords=millionaire+next+door",
        image_alt: "Alex Younger ReadingList The Millionaire Next Door by Thomas J. Stanley & William D. Danko",
        author: "Thomas J. Stanley & William D. Danko",
    },
    {
        title: "The Road to Ruin",
        subtitle: "The Global Elites' Secret Plan for the Next Financial Crisis",
        category: "pol",
        image_address: "road_to_ruin.jpg",
        book_link: "https://www.amazon.com/Road-Ruin-Global-Elites-Financial/dp/1591848083/ref=sr_1_1?s=books&ie=UTF8&qid=1515984429&sr=1-1&keywords=The+Road+to+Ruin+by+James+Rickards",
        image_alt: "Alex Younger ReadingList The Road to Ruin by Jim Rickards",
        author: "Jim Rickards",
    },
    {
        title: "Enlightenment Now",
        subtitle: "The Case for Reason, Science, Humanism, and Progress",
        category: "science",
        image_address: "enlightenment_now.jpg",
        book_link: "https://www.amazon.com/Enlightenment-Now-Science-Humanism-Progress/dp/0525427570/ref=sr_1_2?s=books&ie=UTF8&qid=1526181530&sr=1-2&keywords=enlightenment+now+by+steven+pinker",
        image_alt: "Alex Younger ReadingList Enlightenment Now by Steven Pinker",
        author: "Steven Pinker",
    },
    {
        title: "The Willpower Instinct",
        subtitle: "How Self Control Works, Why it Matters, and What You Can Do to Get More of It",
        category: "productivity",
        image_address: "willpower_instinct.jpg",
        book_link: "https://www.amazon.com/Willpower-Instinct-Self-Control-Works-Matters/dp/1583335080/ref=sr_1_2?s=books&ie=UTF8&qid=1515923129&sr=1-2&keywords=willpower+instinct+by+kelly+mcgonigal",
        image_alt: "Alex Younger ReadingList The Willpower Instinct by Kelly McGonigal, Phd",
        author: "Kelly McGonigal, Phd",
    },
    {
        title: "Economics in One Lesson",
        subtitle: "The Shortest and Surest Way to Understand Basic Economics",
        category: "econ",
        image_address: "economics_one_lesson.jpg",
        book_link: "https://www.amazon.com/Henry-Hazlitt-Economics-One-Lesson/dp/B004LNZ5H0/ref=sr_1_5?s=books&ie=UTF8&qid=1515985408&sr=1-5&keywords=economics+in+one+lesson+henry+hazlitt",
        image_alt: "Alex Younger ReadingList Economics in One Lesson by Henry Hazlitt",
        author: "Henry Hazlitt",
    },   
    {
        title: "The Richest Man in Babylon",
        category: "finance",
        image_address: "richest_man_babylon.jpg",
        book_link: "https://www.amazon.com/Richest-Man-Babylon-George-Clason/dp/1640950494/ref=sr_1_1_sspa?keywords=richest+man+in+babylon&qid=1555294196&s=gateway&sr=8-1-spons&psc=1",
        image_alt: "Alex Younger ReadingList The Richest Man in Babylon by George Clason",
        author: "George Clason",
    },
    {
        title: "The Gulag Archipeligo",
        subtitle: "1918-1956: An Experiment in Literary Investigation",
        category: "history",
        image_address: "gulag.jpg",
        book_link: "https://www.amazon.com/Gulag-Archipelago-Aleksandr-Solzhenitsyn/dp/1843430851",
        image_alt: "Alex Younger ReadingList The Gulag Archipeligo by Alexander Solzhenitsyn",
        author: "Alexander Solzhenitsyn",
    },
    {
        title: "Becoming Your Own Banker",
        subtitle: "Unlock the Infinite Banking Concept",
        category: "finance",
        image_address: "infinite_banking.jpg",
        book_link: "https://www.amazon.com/Becoming-Your-Banker-Nelson-Nash-ebook/dp/B0080K8EL4",
        image_alt: "Alex Younger ReadingList Becoming Your Own Banker by R. Nelson Nash",
        author: "R. Nelson Nash",
    },
    {
        title: "Free Will",
        category: "philosophy",
        image_address: "free_will.jpg",
        book_link: "https://www.amazon.com/Free-Will-Harris-Sam-Paperback/dp/B011SJZJ8O/ref=sr_1_3?s=books&ie=UTF8&qid=1517011043&sr=1-3&keywords=free+will+sam+harris",
        image_alt: "Alex Younger ReadingList Free Will by Sam Harris",
        author: "Sam Harris",
    },
    {
        title: "Influence",
        subtitle: "The Psychology of Persuasion",
        category: "psych",
        image_address: "influence.jpg",
        book_link: "https://www.amazon.com/Influence-Psychology-Persuasion-Robert-Cialdini/dp/006124189X/ref=sr_1_1?s=books&ie=UTF8&qid=1515922756&sr=1-1&keywords=influence+robert+cialdini",
        image_alt: "Alex Younger ReadingList Influence by Robert Cialdini",
        author: "Robert Cialdini",
    },
    {
        title: "Ordinary Men",
        subtitle: "Reserve Police Battalion 101 and the Final Solution in Poland",
        category: "history",
        image_address: "ordinary_men.jpg",
        book_link: "https://www.amazon.com/Ordinary-Men-Reserve-Battalion-Solution/dp/0062303023/ref=pd_lpo_sbs_14_img_0?_encoding=UTF8&psc=1&refRID=905FVFHBW6S35NKN4CWB",
        image_alt: "Alex Younger ReadingList Ordinary Men by Christopher R. Browning",
        author: "Christopher R. Browning",
    },
    {
        title: "Socialism",
        subtitle: "An Economic and Sociological Analysis",
        category: "econ",
        image_address: "socialism.jpg",
        book_link: "https://mises.org/library/socialism-economic-and-sociological-analysis",
        image_alt: "Alex Younger ReadingList Socialism by Ludwig Von Mises",
        author: "Ludwig Von Mises",
    },
    {
        title: "The Power of Body Language",
        subtitle: "An Ex-FBI Agent's System for Speed Reading People",
        category: "psych",
        image_address: "body_language.jpg",
        book_link: "https://www.amazon.com/Power-Body-Language-Ex-FBI-Speed-Reading/dp/B00OH795TO/ref=sr_1_2?ie=UTF8&qid=1515983461&sr=8-2&keywords=the+power+of+body+language+joe+navarro",
        image_alt: "Alex Younger ReadingList The Power of Body Language by Joe Navarro",
        author: "Joe Navarro",
    },
    {
        title: "What Has Government Done to Our Money",
        subtitle: "and The Case for a 100 Percent Gold Dollar",
        category: "econ",
        image_address: "government_money.jpg",
        book_link: "https://mises.org/library/what-has-government-done-our-money",
        image_alt: "Alex Younger ReadingList What Has Government Done to Our Money by Murray Rothbard",
        author: "Murray Rothbard",
    },
    {
        title: "Computer Science Distilled",
        subtitle: "Learn the Art of Computational Problem Solving",
        category: "tech",
        image_address: "computer_science_distilled.jpg",
        book_link: "https://www.amazon.com/Computer-Science-Distilled-Computational-Problems/dp/0997316020",
        image_alt: "Alex Younger ReadingList Computer Science Distilled by Wladston Ferreira Filho",
        author: "Wladston Ferreira Filho",
    },
    {
        title: "Show Your Work",
        subtitle: "10 Ways to Share Your Creativity and Get Discovered",
        category: "productivity",
        image_address: "show_your_work.jpg",
        book_link: "https://www.amazon.com/Show-Your-Work-Austin-Kleon/dp/076117897X/ref=sr_1_1?s=books&ie=UTF8&qid=1520050953&sr=1-1&keywords=show+your+work",
        image_alt: "Alex Younger ReadingList Show Your Work by Austin Kleon",
        author: "Austin Kleon",
    },
    {
        title: "Moonwalking With Einstein",
        subtitle: "The Art and Science of Remembering Everything",
        category: "science",
        image_address: "moonwalking.jpg",
        book_link: "https://www.amazon.com/Moonwalking-Einstein-Science-Remembering-Everything/dp/0143120530/ref=sr_1_1?s=books&ie=UTF8&qid=1551049996&sr=1-1&keywords=moonwalking+with+einstein+by+joshua+foer",
        image_alt: "Alex Younger ReadingList Moonwalking With Einstein by Joshua Foer",
        author: "Joshua Foer",
    },
    {
        title: "Basic Economics",
        subtitle: "A Common Sense Guide to the Economy",
        category: "econ",
        image_address: "basic_econ.jpg",
        book_link: "https://www.amazon.com/Basic-Economics-Thomas-Sowell/dp/0465060730/ref=sr_1_1?hvadid=241666587059&hvdev=c&hvlocphy=9028905&hvnetw=g&hvpos=1t1&hvqmt=e&hvrand=17298452046633619559&hvtargid=kwd-437964245&keywords=basic+economics+thomas+sowell&qid=1555298558&s=gateway&sr=8-1",
        image_alt: "Alex Younger ReadingList Basic Economics by Thomas Sowell",
        author: "Thomas Sowell",
    },
    {
        title: "The Book on Rental Property Investing",
        subtitle: "How to create wealth and passive income through smart buy & hold real estate investing",
        category: "finance",
        image_address: "rental_property.jpg",
        book_link: "https://www.amazon.com/Book-Rental-Property-Investing-Intelligent/dp/099071179X/ref=sr_1_3?s=books&ie=UTF8&qid=1533872549&sr=1-3&keywords=rental+property+investing",
        image_alt: "Alex Younger ReadingList The Book on Rental Property Investing by Brandon Turner",
        author: "Brandon Turner",
    },
    {
        title: "Steal the Show",
        subtitle: "How to Guarantee a Standing Ovation for All the Performances in Your Life",
        category: "productivity",
        image_address: "steal_the_show.jpg",
        book_link: "https://www.amazon.com/Steal-Show-Interviews-Deal-Closing-Performances/dp/0544800842/ref=sr_1_1?s=books&ie=UTF8&qid=1515984539&sr=1-1&keywords=Steal+the+Show+by+Michael+Port",
        image_alt: "Alex Younger ReadingList Steal the Show by Michael Port",
        author: "Michael Port",
    },
    {
        title: "Crucial Conversations",
        subtitle: "Tools for Talking When the Stakes are High",
        category: "peopleskill",
        image_address: "crucial_conversations.jpg",
        book_link: "https://www.amazon.com/Crucial-Conversations-Talking-Stakes-Second/dp/0071771328/ref=sr_1_1?s=books&ie=UTF8&qid=1515984205&sr=1-1&keywords=crucial+conversations",
        image_alt: "Alex Younger ReadingList Crucial Conversations by Kelly Patterson",
        author: "Kelly Patterson",
    },
    {
        title: "What You Should Know About Inflation",
        category: "econ",
        image_address: "inflation.jpg",
        book_link: "https://mises.org/library/what-you-should-know-about-inflation-0",
        image_alt: "Alex Younger ReadingList What You Should Know About Inflation by Henry Hazlitt",
        author: "Henry Hazlitt",
    },
    {
        title: "Behave",
        subtitle: "The Biology of Humans at Our Best and at Our Worst",
        category: "science",
        image_address: "behave.jpg",
        book_link: "https://www.amazon.com/Behave-Biology-Humans-Best-Worst-ebook/dp/B01IAUGC5S/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1515981537&sr=1-1&keywords=behave+robert+sapolsky",
        image_alt: "Alex Younger ReadingList Behave by Robert M. Sapolsky",
        author: "Robert M. Sapolsky",
    },
    {
        title: "A Conflict of Visions",
        subtitle: "Ideological Origins of Political Struggles",
        category: "econ",
        image_address: "conflict_visions.jpg",
        book_link: "https://www.amazon.com/Conflict-Visions-Ideological-Political-Struggles/dp/0465002056/ref=sr_1_1?s=books&ie=UTF8&qid=1551050535&sr=1-1&keywords=conflict+of+visions",
        image_alt: "Alex Younger ReadingList A Conflict of Visions by Thomas Sowell",
        author: "Thomas Sowell",
    },
    {
        title: "America's Great Depression",
        category: "history",
        image_address: "great_depression.jpg",
        book_link: "https://mises.org/library/americas-great-depression",
        image_alt: "Alex Younger ReadingList America's Great Depression by Murray Rothbard",
        author: "Murray Rothbard",
    },
    {
        title: "The Fatal Conceit",
        subtitle: "The Errors of Socialism",
        category: "econ",
        image_address: "fatal_conceit.jpg",
        book_link: "https://www.amazon.com/Fatal-Conceit-Errors-Socialism-Collected/dp/0226320669/ref=sr_1_1?s=books&ie=UTF8&qid=1551050285&sr=1-1&keywords=fatal+conceit+hayek",
        image_alt: "Alex Younger ReadingList The Fatal Conceit by F.A. Hayek",
        author: "F.A. Hayek",
    },
    {
        title: "A Short History of Man",
        subtitle: "Progress and Decline",
        category: "history",
        image_address: "history_of_man.jpg",
        book_link: "https://www.amazon.com/Short-History-Man-Progress-Decline/dp/1610165918/ref=sr_1_1?s=books&ie=UTF8&qid=1515984984&sr=1-1&keywords=a+short+history+of+man+hoppe",
        image_alt: "Alex Younger ReadingList A Short History of Man by Hans-Hermann Hoppe",
        author: "Hans-Hermann Hoppe",
    },
    {
        title: "The CEO Tightrope",
        subtitle: "How to Master the Balancing Act of a CEO",
        category: "biz",
        image_address: "ceo_tightrope.jpg",
        book_link: "https://www.amazon.com/CEO-Tightrope-Master-Balancing-Successful/dp/1626341060/ref=sr_1_1?s=books&ie=UTF8&qid=1515986582&sr=1-1&keywords=the+ceo+tightrope+by+joel+trammell",
        image_alt: "Alex Younger ReadingList The CEO Tightrope by Joel Trammell",
        author: "Joel Trammell",
    },
    {
        title: "The Little Book of Bull Moves",
        subtitle: "How to Keep Your Portfolio Up When the Market is Up, Down, or Sideways",
        category: "finance",
        image_address: "bull_moves.jpg",
        book_link: "https://www.amazon.com/Little-Book-Moves-Updated-Expanded/dp/0470643994/ref=sr_1_2?s=books&ie=UTF8&qid=1515983796&sr=1-2&keywords=the+little+book+of+bull+moves+peter+schiff",
        image_alt: "Alex Younger ReadingList The Little Book of Bull Moves by Peter Schiff",
        author: "Peter Schiff",
    },
    {
        title: "The 4-Hour Workweek",
        subtitle: "Escape 9-5, Live Anywhere, and Join the New Rich",
        category: "biz",
        image_address: "4_hour.jpg",
        book_link: "https://www.amazon.com/4-Hour-Workweek-Escape-Live-Anywhere/dp/0307465357/ref=sr_1_1?s=books&ie=UTF8&qid=1515985483&sr=1-1&keywords=the+four+hour+work+week",
        image_alt: "Alex Younger ReadingList The 4 Hour Workweek by Tim Ferriss",
        author: "Tim Ferriss",
    },
    {
        title: "The 48 Laws of Power",
        category: "productivity",
        image_address: "48_laws.jpg",
        book_link: "https://www.amazon.com/48-Laws-Power-Robert-Greene/dp/0140280197/ref=sr_1_1?keywords=48+laws+of+power&qid=1555294105&s=gateway&sr=8-1",
        image_alt: "Alex Younger ReadingList The 48 Laws of Power by Robert Greene",
        author: "Robert Greene",
    },
    {
        title: "Hawk",
        subtitle: "Occupation: Skateboarder",
        category: "autobio",
        image_address: "hawk.jpg",
        book_link: "https://www.amazon.com/Hawk-Occupation-Skateboarder-Tony/dp/0060958316/ref=sr_1_2?ie=UTF8&qid=1521363258&sr=8-2&keywords=hawk+by+tony+hawk&dpID=51TnMCb8ToL&preST=_SY291_BO1,204,203,200_QL40_&dpSrc=srch",
        image_alt: "Alex Younger ReadingList Hawk by Tony Hawk",
        author: "Tony Hawk",
    },
    {
        title: "The Intelligent Investor",
        subtitle: "The Definitive Book on Value Investing",
        category: "finance",
        image_address: "intelligent_investor.jpg",
        book_link: "https://www.amazon.com/Intelligent-Investor-Definitive-Investing-Essentials/dp/0060555661/ref=sr_1_1?s=books&ie=UTF8&qid=1515987281&sr=1-1&keywords=the+intelligent+investor+by+benjamin+graham",
        image_alt: "Alex Younger ReadingList The Intelligent Investor by Benjamin Graham",
        author: "Benjamin Graham",
    },
    {
        title: "The Lean Startup",
        subtitle: "How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
        category: "biz",
        image_address: "lean_startup.jpg",
        book_link: "https://www.amazon.com/Lean-Startup-Entrepreneurs-Continuous-Innovation/dp/0307887898/ref=sr_1_3?s=books&ie=UTF8&qid=1515983642&sr=1-3&keywords=the+lean+startup+eric+ries",
        image_alt: "Alex Younger ReadingList The Lean Startup by Eric Ries",
        author: "Eric Ries",
    },
    {
        title: "The Politically Incorrect Guide to American History",
        category: "history",
        image_address: "politically_incorrect.jpg",
        book_link: "https://www.amazon.com/Politically-Incorrect-Guide-American-History/dp/B000CCE4JE/ref=sr_1_1?ie=UTF8&qid=1517017239&sr=8-1&keywords=politically+incorrect+guide+to+american+history",
        image_alt: "Alex Younger ReadingList The Politically Correct Guide to American History by Thomas e. Woods",
        author: "Thomas E. Woods",
    },
    {
        title: "The Progressive Era",
        category: "history",
        image_address: "progressive_era.jpg",
        book_link: "https://www.amazon.com/Progressive-Era-Murray-Rothbard-ebook/dp/B076B4SW5T/ref=sr_1_1?s=books&ie=UTF8&qid=1551050667&sr=1-1&keywords=progressive+era+murray",
        image_alt: "Alex Younger ReadingList The Progressive Era by Murray N. Rothbard",
        author: "Murray N. Rothbard",
    },
    {
        title: "To Sell is Human",
        subtitle: "The Surprising Truth About Moving Others",
        category: "biz",
        image_address: "sell_is_human.jpg",
        book_link: "https://www.amazon.com/Sell-Human-Surprising-Moving-Others/dp/1594631905/ref=sr_1_3?s=books&ie=UTF8&qid=1515985359&sr=1-3&keywords=to+sell+is+human",
        image_alt: "Alex Younger ReadingList To Sell is Human by Daniel H. Pink",
        author: "Daniel H. Pink",
    },
    {
        title: "Born for This",
        category: "biz",
        image_address: "born_for_this.jpg",
        book_link: "https://www.amazon.com/Born-This-Find-Work-Meant/dp/1101903988/ref=sr_1_1?s=books&ie=UTF8&qid=1515985831&sr=1-1&keywords=born+for+this+chris+guillebeau",
        image_alt: "Alex Younger ReadingList Born for This by Chris Guillebeau",
        author: "Chris Guillebeau",
    },
    {
        title: "Anatomy of the State",
        category: "pol",
        image_address: "anatomy_of_state.jpg",
        book_link: "https://mises.org/library/anatomy-state",
        image_alt: "Alex Younger ReadingList Anatomy of the State by Murray Rothbard",
        author: "Murrary Rothbard",
    },
    {
        title: "The $100 Startup",
        subtitle: "Reinvent the Way You Make a Living, Do What You Love, and Create a New Future",
        category: "biz",
        image_address: "100_startup.jpg",
        book_link: "https://www.amazon.com/100-Startup-Reinvent-Living-Create/dp/0307951529/ref=sr_1_1?s=books&ie=UTF8&qid=1515986114&sr=1-1&keywords=the+%24100+startup+by+chris+guillebeau",
        image_alt: "Alex Younger ReadingList The $100 Startup by Chris Guillebeau",
        author: "Chris Guillebeau",
    },
    {
        title: "The Law",
        category: "econ",
        image_address: "the_law.jpg",
        book_link: "https://www.amazon.com/Law-Frederic-Bastiat/dp/1440496064/ref=sr_1_1_sspa?crid=7ZMH94ILX0L6&keywords=the+law+by+frederic+bastiat&qid=1555294381&s=books&sprefix=the+law+by+%2Cstripbooks%2C186&sr=1-1-spons&psc=1",
        image_alt: "Alex Younger ReadingList The Law by Frederic Bastiat",
        author: "Frederic Bastiat",
    },
    {
        title: "Why Zebras Don't Get Ulcers",
        subtitle: "The Acclaimed Guide to Stress, Stress-Related Diseases, and Coping",
        category: "science",
        image_address: "zebras_dont_get_ulcers.jpg",
        book_link: "https://www.amazon.com/Why-Zebras-Dont-Ulcers-Third/dp/0805073698/ref=sr_1_1?s=books&ie=UTF8&qid=1515986523&sr=1-1&keywords=Why+Zebras+Don%27t+Get+Ulcers+by+Robert+M.+Sapolsky",
        image_alt: "Alex Younger ReadingList Why Zebras Don't Get Ulcers by Robert M. Sapolsky",
        author: "Robert M. Sapolsky",
    },
    {
        title: "The Three Languages of Politics",
        subtitle: "Talking Across the Political Divides",
        category: "pol",
        image_address: "three_languages_politics.jpg",
        book_link: "https://www.amazon.com/Three-Languages-Politics-Talking-Political/dp/1944424466/ref=sr_1_1?s=books&ie=UTF8&qid=1515986807&sr=1-1&keywords=The+Three+Languages+of+Politics+by+Arnold+Kling",
        image_alt: "Alex Younger ReadingList The Three Languages of Politics by Arnold Kling",
        author: "Arnold Kling",
    },
    {
        title: "Never Eat Alone",
        subtitle: "And Other Secrets to Success, One Relationship at a Time",
        category: "peopleskill",
        image_address: "never_eat_alone.jpg",
        book_link: "https://www.amazon.com/Never-Eat-Alone-Expanded-Updated/dp/0385346654/ref=sr_1_1?s=books&ie=UTF8&qid=1515987002&sr=1-1&keywords=never+eat+alone+by+keith+ferrazzi",
        image_alt: "Alex Younger ReadingList Never Eat Alone by Keith Ferrazzi",
        author: "Keith Ferrazzi",
    },
    {
        title: "Darkness Visible",
        subtitle: "A Memoir of Madness",
        category: "misc",
        image_address: "darkness_visible.jpg",
        book_link: "https://www.amazon.com/Darkness-Visible-Madness-William-Styron/dp/0679736395/ref=sr_1_1?s=books&ie=UTF8&qid=1515987132&sr=1-1&keywords=darkness+visible+william+styron",
        image_alt: "Alex Younger ReadingList Darkness Visible by William Styron",
        author: "William Styron",
    },
    {
        title: "Ignore Everybody",
        subtitle: "And 39 Other Keys to Creativity",
        category: "misc",
        image_address: "ignore_everybody.jpg",
        book_link: "https://www.amazon.com/Ignore-Everybody-Other-Keys-Creativity/dp/159184259X/ref=sr_1_1?s=books&ie=UTF8&qid=1515985570&sr=1-1&keywords=Ignore+Everybody+by+Hugh+Macleod",
        image_alt: "Alex Younger ReadingList Ignore Everybody by Hugh Macleod",
        author: "Hugh MacLeod",
    },
    {
        title: "Economic Controversies",
        category: "econ",
        image_address: "economic_controversies.jpg",
        book_link: "https://mises.org/library/economic-controversies",
        image_alt: "Alex Younger ReadingList Economic Controversies by Murry Rothbard",
        author: "Murray Rothbard",
    },
    {
        title: "Spacetime Physics",
        subtitle: "Introduction to Special Relativity; Second Edition",
        category: "science",
        image_address: "spacetime_physics.jpg",
        book_link: "https://www.amazon.com/Spacetime-Physics-Edwin-F-Taylor/dp/0716723271/ref=sr_1_1?s=books&ie=UTF8&qid=1517016672&sr=1-1&keywords=spacetime+physics+taylor+and+wheeler",
        image_alt: "Alex Younger ReadingList Spacetime Physics by Edwin F. Taylor & John Archibald Wheeler",
        author: "Edwin F. Taylor & John Archibald Wheeler",
    }])